language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

before_script:
  - composer self-update
  - composer install --no-scripts --no-interaction --dev
  - composer dump-autoload -o
  - phpenv config-add ./tests/travis.ini

after_script:
    - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
